"""
Pydantic schemas for content structure.
"""
from typing import Optional
from pydantic import BaseModel, Field


class Question(BaseModel):
    """Single question in a stage."""
    id: str = Field(..., description="Question ID, e.g., 'q2-1'")
    type: str = Field(..., description="Question type: concept, calculation, coding")
    difficulty: str = Field(..., description="Difficulty: easy, medium, hard")
    question: str = Field(..., description="Question text")
    hint: Optional[str] = Field(None, description="Hint for the question")
    options: Optional[list[str]] = Field(None, description="Options for multiple choice")
    answer: str = Field(..., description="Correct answer")
    explanation: str = Field(..., description="Explanation of the answer")


class TestCase(BaseModel):
    """Test case for coding task."""
    input: str = Field(..., description="Input to the program")
    expected: str = Field(..., description="Expected output")
    hidden: bool = Field(False, description="Whether test case is hidden")


class StageContent(BaseModel):
    """Complete stage content generated by the orchestrator."""
    stage_id: int = Field(..., description="Stage ID")
    stage_name: str = Field(..., description="Stage name, e.g., 'control-flow'")
    handbook: str = Field(..., description="Learning handbook in markdown")
    questions: list[Question] = Field(..., description="List of questions")
    baseline_code: Optional[str] = Field(None, description="Baseline code template")
    test_cases: list[TestCase] = Field(default_factory=list, description="Test cases")
    summary: Optional[str] = Field(None, description="Stage summary")

    # Metadata
    plan_output: Optional[str] = Field(None, description="Original plan output")
    generate_iteration: int = Field(1, description="Generation iteration number")

    class Config:
        json_schema_extra = {
            "example": {
                "stage_id": 3,
                "stage_name": "functions",
                "handbook": "# Python 函数学习手册...",
                "questions": [
                    {
                        "id": "q3-1",
                        "type": "concept",
                        "difficulty": "easy",
                        "question": "...",
                        "options": None,
                        "answer": "A",
                        "explanation": "..."
                    }
                ],
                "baseline_code": "def solve():\n    pass",
                "test_cases": [
                    {"input": "5", "expected": "15", "hidden": False}
                ]
            }
        }
