#!/usr/bin/env python3
import os

BASE = "/Users/jimfu/Work/huixue/ziyuan_normalized"
SH_PATH = "/tmp/create_exact_dummies.sh"

mp4_b64 = "AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAAIZnJlZQAACsVtZGF0AAACrgYF//+//u4AAAMqZ2RlWwLqBQDywEQAAAAAABBAAQACQQwH/m2/7X+AAAgEAAAEAAAgEAAAEAAA//8P//7//wAA/+sAQAACqWdvc2CAgIAAAAI0bW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAAD6AAABwAAAAABAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAwY2xpcAAAACR0cmFwAAAAAHB2ZGkAAAAAAAAAAAACAAAAFHRyZWwAAAAAAAAAAAADAAAAABZlZHRzAAAADmVsc3QAAAAAAAAAAQAAA98AAAAAAAABAAAAAAJmdHJhawAAAFx0a2hkAAAAAwAAAAAAAAAAAAAAAQAAAAAAAAAD6AAABwAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAEGVkdHMAAAAIZWxzdAAAAAAAAAABAAEAAA1gbWRpYQAAAChtZGhkAAAAAAAAAAAAAAAAAAB1MAAAvSAAACc0AAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAFZpZGVvSGFuZGxlcgAAAAIEbWluZgAAABR2bWhkAAAAAQAAAAAAAAAAAAAAJGRpbmYAAAAcYnJlZgAAABR1cmwgAAAAAQAAAAAAAAAAAAFpc3RibAAAACZzdHNkAAAAAAAAAAEAAAASYXZjMQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAABAAEASAAAAEgAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABj//wAAAABzdHRzAAAAAAAAAAEAAAABAAACrwAAABRzdHNzAAAAAAAAAAEAAAABAAAAHHN0c2MAAAAAAAAAAQAAAAEAAAABAAAAAQAAABBzdHN6AAAAAAAAAAAAAAABAAAAOAAAAChzdGNvAAAAAAAAAAEAAAAUCQAAAEB1ZHRhAAAAOG1ldGEAAAAAAAAAIWhkbHIAAAAAAAAAAG1kaXJhcHBsAAAAAAAAAAAAAAAABGlsc3QAAAAcc2NlbgAAABRkYXRhAAAAAQAAAAAAMQAAAA=="
pptx_b64 = "UEsDBBQAAAAIAAAAAM1TzUIAAADyAQAAEAAAAHByb3BzL2FwcC54bWwTzEvMTdUrzUlMKS5xTEkxD/Hz9w12M3Q1MDTTy0xNKdYrykxLzU2sSFUryS+yKikqiS9PzE1V0i12zkwpzUnVT0rM01HKyyxKTrV2T2X1S2WzTWQNZM0zNDdRM1I1UrP0MDFVNjKzMrdUy8ksScxLBWoGAK9oGgB2A1PqAAAA//8DAFBLAwQUAAAACAAAAABk1U1CAAAAIgMAABAAcHJvcHMvY29yZS54bWwAAAD//wMAUEsDBBQAAAAIAAAAAFNSTkIAAABsBQAAEABkb2NQcm9wcy9hcHAueG1sAH0AABfA0AAACQAAAAAA//8DAFBLAwQUAAAACAAAAACyP01CAAAAggwAABABkb2NQcm9wcy9jb3JlLnhtbAAAH8AAAAkAAAAAAP//AwBQSwMEFAAAAAgAAAAAi2ZNQgAAAOQoAAAQAGEA/wAAAQAAAP//AwBQSwcIa+FwE1AAAABPBAAAUEsBAhQAFAAAAAgAAAAAAM1TzUIAAADyAQAAEAAAAAAAAAAAAAAAAAAAAAAAcHJvcHMvY29yZS54bWwA/wAAUEsBAhQAFAAAAAgAAAAAi2ZNQgAAAOQoAAAQAGEA/wAAAAAAAAAAAAAAHwQAAEAAAAA="

with open(SH_PATH, "w") as f:
    f.write("#!/bin/bash\n")
    f.write("VOL_DIR='/var/lib/docker/volumes/ziyuan-data/_data'\n")
    f.write(f"cat << 'B64' > /tmp/dummy.mp4.b64\n{mp4_b64}\nB64\n")
    f.write(f"cat << 'B64' > /tmp/dummy.pptx.b64\n{pptx_b64}\nB64\n")
    f.write("base64 -d /tmp/dummy.mp4.b64 > /tmp/dummy.mp4\n")
    f.write("base64 -d /tmp/dummy.pptx.b64 > /tmp/dummy.pptx\n\n")

    for root, dirs, files in os.walk(BASE):
        if 'assets/videos' in root or 'assets/slides' in root:
            for file in files:
                if file.endswith('.mp4'):
                    rel_dir = os.path.relpath(root, BASE)
                    f.write(f"echo 'kejixueyuan@dashuju' | sudo -S mkdir -p \"$VOL_DIR/{rel_dir}\"\n")
                    f.write(f"echo 'kejixueyuan@dashuju' | sudo -S cp /tmp/dummy.mp4 \"$VOL_DIR/{rel_dir}/{file}\"\n")
                elif file.endswith('.pptx'):
                    rel_dir = os.path.relpath(root, BASE)
                    f.write(f"echo 'kejixueyuan@dashuju' | sudo -S mkdir -p \"$VOL_DIR/{rel_dir}\"\n")
                    f.write(f"echo 'kejixueyuan@dashuju' | sudo -S cp /tmp/dummy.pptx \"$VOL_DIR/{rel_dir}/{file}\"\n")
print(f"Generated {SH_PATH}")
